# Dockerfile.migrations
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN dotnet restore "portafolio.backend.API.csproj"
RUN dotnet build "portafolio.backend.API.csproj" -c Release -o /app/build
RUN dotnet publish "portafolio.backend.API.csproj" -c Release -o /app/publish

# Instalar dotnet-ef (si no está ya instalado)
RUN dotnet tool install --version 9.0.1 --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"